//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandenStedenTalen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taal
    {
        public Taal()
        {
            this.Landen = new HashSet<Land>();
        }
    
        public string TaalCode { get; set; }
        public string Naam { get; set; }
    
        public virtual ICollection<Land> Landen { get; set; }
    }
}
